# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcstop < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.0/dcstop_Darwin_x86_64.tar.gz"
      sha256 "55974f2deff1cb17a9ea3839f4759589c6776009448da9a0b2813932e96698e1"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.0/dcstop_Darwin_arm64.tar.gz"
      sha256 "8fcad09b6189b10c343ffea4f3e9efe392f333d4f0e10685a1b03dd544c29e42"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.0/dcstop_Linux_x86_64.tar.gz"
      sha256 "ae2012a437e87a2a008f1373a51a700ccf3db521e75ee29d3ae6e20eb3feba24"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.0/dcstop_Linux_arm64.tar.gz"
      sha256 "ed62f3a89310c101ab666abfa27374eca203c66fb88cd0cb781667ace0cea922"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end
end
