# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcstop < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.2/dcstop_Darwin_x86_64.tar.gz"
      sha256 "68998609e907a8691a558159c2771fe779e04825834b17c48ed7d0aea1555761"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.2/dcstop_Darwin_arm64.tar.gz"
      sha256 "58fd99c222f43cd05f2cd0557b00006916796a84502188db91f80a4bb212d2c4"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.2/dcstop_Linux_x86_64.tar.gz"
      sha256 "f469438ee210e0d0b0320569f77ff900e902d3f5ee2b332b0e96fa7bc02b11e4"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.2/dcstop_Linux_arm64.tar.gz"
      sha256 "bc3aacb3dcba06eb98a8e1511c58788c81851baa0030c5f70bb3f854d445d62e"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end
end
