# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcstop < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.1/dcstop_Darwin_x86_64.tar.gz"
      sha256 "c724d4c17a6513030e0a20d05bacd184c9e5e91ca4d8b678ac461c990b39c3de"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.1/dcstop_Darwin_arm64.tar.gz"
      sha256 "022a96b8602dd7ade97a6235bc6b28da94bc04b8f6df14a2e1271b394ad8a619"

      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.1/dcstop_Linux_x86_64.tar.gz"
      sha256 "2193c62562bae662cd7d2dc70ee8d35abda560a281bfd47c065a13748bf6addc"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-shimada/dcstop/releases/download/v0.1.1/dcstop_Linux_arm64.tar.gz"
      sha256 "a1a2d1cb6c7e212be580512dab5fa4cbcf9f64174b2aef09ff419b3bac4c7ba6"
      def install
        bin.install "dcstop"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion bash")
        (bash_completion/"dcstop").write output

        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion zsh")
        (zsh_completion/"_dcstop").write output

        # Install fish completion
        output = Utils.safe_popen_read("#{bin}/dcstop completion fish")
        (fish_completion/"dcstop.fish").write output
      end
    end
  end
end
