# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcstop" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "d7321aea4ecec19a175a8a6679657aa74c4b7a17092c2a08774cc8fd70f04f3b"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5d73e13d9e459c4cc59c153c9d4debd8995fcbd7340c185aed2fe18ea6d62cd9"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "287bb8e7c938cff6ada4fb51f622b9b1fdc548ef7aa84a6095d4fb50f544db7a"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d3f18d628e1d00c37c190630299063c7fd4561c7f6cfd432579c35042a5f4884"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_arm64.tar.gz"
    end
  end

  name "dcstop"
  desc "A CLI tool to easily stop devcontainers"
  homepage "https://github.com/dev-shimada/dcstop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcstop"

  # No zap stanza required

end
