# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcstop" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "e773ea64839c4cdd9033d4f424ce982b239db72da49c350068d16ba4930b915e"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "61026214d572e09aa5d765fe2be89cf08469a89f8c9f222bbda3a0298cdc7cd3"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad80f91e0dc79e8470f920b394a74b805da8e1da4c70d72df6f5977112513c1d"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40a5245c28d2d6408c7185a91162c8d12f168aa7320225699036a6c6862a30b1"
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_arm64.tar.gz"
    end
  end

  name "dcstop"
  desc "A CLI tool to easily stop devcontainers"
  homepage "https://github.com/dev-shimada/dcstop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcstop"

  # No zap stanza required

end
