# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcstop" do
  name "dcstop"
  desc "A CLI tool to easily stop devcontainers"
  homepage "https://github.com/dev-shimada/dcstop"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcstop"

  on_macos do
    on_intel do
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_x86_64.tar.gz"
      sha256 "b968c582e1ae57ff2644a2ff18d3d6b4f0ca749cf354255373513526c56f153b"
    end
    on_arm do
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Darwin_arm64.tar.gz"
      sha256 "63ddec967483670261a82a67d6841597dddab28d703f70594919abceb6cad5db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_x86_64.tar.gz"
      sha256 "07afe2736b9386e607c18677186ee851366030f0e6de386fe232268561e33a41"
    end
    on_arm do
      url "https://github.com/dev-shimada/dcstop/releases/download/v#{version}/dcstop_Linux_arm64.tar.gz"
      sha256 "a25ae9d599940d26c641bef3816d7b009220ee38fafa4c57dad34fe6d579702d"
    end
  end

  # No zap stanza required
end
